#!/bin/zsh

# Script for update HomeBrew packages and routine maintenace

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${RED}Updating Brew...${NC}"
brew update
echo -e "${RED}Upgrading Brew packages...${NC}"
brew upgrade
echo -e "${RED}Cleanup Brew...${NC}"
brew cleanup


echo -e "\n${RED}Start updating Oh My Zsh...${NC}"
source ~/.zshrc
omz update
